// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf7oNMz_2sjExYN1p-Mns8tuvWoaJBRq0',
    appId: '1:867068954619:web:a5a83607af1603bae5ad5e',
    messagingSenderId: '867068954619',
    projectId: 'attendance-84a3d',
    authDomain: 'attendance-84a3d.firebaseapp.com',
    storageBucket: 'attendance-84a3d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvAXcgt979navJYhByJKDYv4dpG8BF7LY',
    appId: '1:867068954619:android:2439497e0d30c06de5ad5e',
    messagingSenderId: '867068954619',
    projectId: 'attendance-84a3d',
    storageBucket: 'attendance-84a3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW5xTxI8tRLK9sVtlLoc4SK4WtVRqDaOw',
    appId: '1:867068954619:ios:b97a76ade9597c99e5ad5e',
    messagingSenderId: '867068954619',
    projectId: 'attendance-84a3d',
    storageBucket: 'attendance-84a3d.appspot.com',
    iosBundleId: 'com.example.attandance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW5xTxI8tRLK9sVtlLoc4SK4WtVRqDaOw',
    appId: '1:867068954619:ios:ce1206c558a0774ee5ad5e',
    messagingSenderId: '867068954619',
    projectId: 'attendance-84a3d',
    storageBucket: 'attendance-84a3d.appspot.com',
    iosBundleId: 'com.example.attandance.RunnerTests',
  );
}
